app:
  port: 8080
  env: dev

database:
  driver: mysql
  migrate: true
  dsn: fortest:test@tcp(localhost:3307)/fortest?charset=utf8mb4&parseTime=True&loc=Local&timeout=1000ms

redis:
  enable: true
  host: localhost
  port: 16379
  password: DbinggoYjddb
  db: 0
