app:
  port: 8080
  env: pro

database:
  driver: mysql
  migrate: true
  dsn: fortest:test@tcp(123.207.73.185:3307)/fortest?charset=utf8mb4&parseTime=True&loc=Local&timeout=1000ms

redis:
  enable: true
  host: 123.207.73.185
  port: 16379
  password: DbinggoYjddb
  db: 0
